package com.creasmit.bipgo.entity;
// Generated Mar 22, 2021 11:34:11 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Agent generated by hbm2java
 */
public class Agent implements java.io.Serializable {

    private int id;
    private Date dateCreate;
    private Date dateModif;
    private Integer agentCreate;
    private Integer agentModif;
    private String codeActivation;
    private Integer fkIdentite;
    private Integer fkTypeAgent;
    private Integer fkWallet;

    public Agent() {
    }

    public Agent(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getDateCreate() {
        return dateCreate;
    }

    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    public Date getDateModif() {
        return dateModif;
    }

    public void setDateModif(Date dateModif) {
        this.dateModif = dateModif;
    }
    
    public String getCodeActivation() {
        return codeActivation;
    }

    public void setCodeActivation(String codeActivation) {
        this.codeActivation = codeActivation;
    }

    public Integer getAgentCreate() {
        return agentCreate;
    }

    public void setAgentCreate(Integer agentCreate) {
        this.agentCreate = agentCreate;
    }

    public Integer getAgentModif() {
        return agentModif;
    }

    public void setAgentModif(Integer agentModif) {
        this.agentModif = agentModif;
    }

    public Integer getFkIdentite() {
        return fkIdentite;
    }

    public void setFkIdentite(Integer fkIdentite) {
        this.fkIdentite = fkIdentite;
    }

    public Integer getFkTypeAgent() {
        return fkTypeAgent;
    }

    public void setFkTypeAgent(Integer fkTypeAgent) {
        this.fkTypeAgent = fkTypeAgent;
    }

    public Integer getFkWallet() {
        return fkWallet;
    }

    public void setFkWallet(Integer fkWallet) {
        this.fkWallet = fkWallet;
    }
    
}
