package com.creasmit.bipgo.entity;
// Generated Mar 22, 2021 11:34:11 AM by Hibernate Tools 4.3.1

/**
 * Identite generated by hbm2java
 */
public class Identite implements java.io.Serializable {

    private int id;
    private String nom;
    private String postnom;
    private String prenom;
    private String numTel;
    private String email;
    private String carteIdentite;
    private String photo;
    private String adresse;

    public Identite() {
    }

    public Identite(int id) {
        this.id = id;
    }

    public Identite(int id, String nom, String postnom, String prenom, String numTel, String email, String carteIdentite, String photo) {
        this.id = id;
        this.nom = nom;
        this.postnom = postnom;
        this.prenom = prenom;
        this.numTel = numTel;
        this.email = email;
        this.carteIdentite = carteIdentite;
        this.photo = photo;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPostnom() {
        return postnom;
    }

    public void setPostnom(String postnom) {
        this.postnom = postnom;
    }

    public String getPrenom() {
        return prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getNumTel() {
        return numTel;
    }

    public void setNumTel(String numTel) {
        this.numTel = numTel;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getCarteIdentite() {
        return carteIdentite;
    }

    public void setCarteIdentite(String carteIdentite) {
        this.carteIdentite = carteIdentite;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getAdresse() {
        return adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }  

}
