package com.creasmit.bipgo.entity;
// Generated Mar 22, 2021 11:34:11 AM by Hibernate Tools 4.3.1



/**
 * TypeAgent generated by hbm2java
 */
public class TypeAgent  implements java.io.Serializable {


     private int id;
     private String libelle;

    public TypeAgent() {
    }

	
    public TypeAgent(int id) {
        this.id = id;
    }
    public TypeAgent(int id, String libelle) {
       this.id = id;
       this.libelle = libelle;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }




}


