package com.creasmit.bipgo.model;
// Generated Mar 18, 2021 11:02:15 AM by Hibernate Tools 4.3.1



/**
 * Profil generated by hbm2java
 */
public class Profil  implements java.io.Serializable {


     private int id;
     private String nom;
     private String postnom;
     private String prenom;
     private String numTel;
     private String email;
     private String username;
     private String password;
     private Integer fkApplication;
     private String photo;

    public Profil() {
    }

	
    public Profil(int id) {
        this.id = id;
    }
    public Profil(int id, String nom, String postnom, String prenom, String numTel, String email, String username, String password, Integer fkApplication, String photo) {
       this.id = id;
       this.nom = nom;
       this.postnom = postnom;
       this.prenom = prenom;
       this.numTel = numTel;
       this.email = email;
       this.username = username;
       this.password = password;
       this.fkApplication = fkApplication;
       this.photo = photo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPostnom() {
        return this.postnom;
    }
    
    public void setPostnom(String postnom) {
        this.postnom = postnom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getNumTel() {
        return this.numTel;
    }
    
    public void setNumTel(String numTel) {
        this.numTel = numTel;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getFkApplication() {
        return this.fkApplication;
    }
    
    public void setFkApplication(Integer fkApplication) {
        this.fkApplication = fkApplication;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }




}


